spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5433/citronix
    username: citronix
    password: password

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    change-log: db/changelog/master.yaml


